Added browse cards
aloelabs/aloe-web-interface pull request #6
Opened 2022-04-30 02:32 UTC by IanWoodard

Added browse cards using styling defined on Figma. I realize there is a lot of overlap between the BrowseCard component and the PortfolioCard component, and once they are both merged I will work to remove any duplicate code/logic. It is also worth noting that this PR is just for the cards and the overall layout and not the other components on the page.

Pictures below show said cards.
![browsecardnormal](https://user-images.githubusercontent.com/17186604/166087021-3744e5cc-07d2-4bba-8d2b-d0a4cbeee901.PNG)
![browsecardnormal2](https://user-images.githubusercontent.com/17186604/166087025-61a44200-3e0a-4e8e-bea1-b0c931c81ded.PNG)
![browsecardhover](https://user-images.githubusercontent.com/17186604/166087023-526faee4-5ce5-40d9-9d4f-0b89bc5f166a.PNG)
![browsecardsmultiple](https://user-images.githubusercontent.com/17186604/166087024-f530f8ba-89ab-453f-b7a2-aebd4bdf1368.PNG)

2022-05-04 20:52 UTC, IanWoodard commented
@adamegyed I merged the Portfolio Card changes and then removed duplicate code between them. Take a look when you get the chance.

2022-05-11 01:51 UTC, haydenshively commented
I changed the prominent color calc -- now if the logo is mostly black/white but has a pop of color, the pop of color will be chosen. Otherwise LGTM

2022-05-11 02:05 UTC, haydenshively commented
@adamegyed Please take a quick look at the code and then merge ASAP

2022-06-02 15:51 UTC, adamegyed requested changes
Couple small changes and this should be good to go. Thanks for deduplicating code across the portfolio cards!

2022-06-02 15:51 UTC, adamegyed commented on src/components/browse/BrowseCard.tsx
> +    });
This is a dangerous way to use `useEffect` because it can lead to memory leaks. If determining the prominent color really needs an async call, define an inline async function, call it, and have the outer arrow function given to `useEffect` return a cleanup function. This cleanup function should prevent the state-modifying functions - `setToken0Color` and `setToken1Color` - from firing. The easiest way to do this is through a shared flag that is captured by both the async function and the cleanup function, which can be automatically done with closures.

2022-06-02 15:51 UTC, adamegyed commented on src/components/common/TokenPairIcons.tsx
> +        src={token1IconPath || ''}
In the event we don't have a token icon, there's a default icon at `src/assets/svg/tokens/unknown_token.svg` that should be used.

2022-06-02 15:51 UTC, adamegyed commented on src/components/common/TokenPairIcons.tsx
> +const OMIT_TOKEN_BACKGROUND_COLOR = 'transparent';
This is something we might want to change in the future, but OK for this PR. It could look odd, but we'll only know by testing it together with the other pending changes.

2022-06-02 15:51 UTC, adamegyed commented on src/components/common/WideAppPage.tsx
> +}
Fine for now, possibly can be replaced with changes to AppPage in later PRs.

2022-06-02 15:51 UTC, adamegyed commented on src/pages/BlendPoolSelectPage.tsx
> +  }
I'm pretty sure there's a cleaner way to do this with Tailwind, but this is fine for now.

2022-06-02 15:51 UTC, adamegyed commented on src/pages/BlendPoolSelectPage.tsx
> +          {pools.map((pool, index, array) => {
Can omit `, array` when unused.

2022-06-02 15:51 UTC, adamegyed commented on src/util/Colors.ts
> +function rgb_to_hsv(rgb: number[]) {
Missing docstring and return type annotation.

2022-06-02 15:51 UTC, adamegyed commented on src/util/Colors.ts
>  export async function getProminentColor(path: string) {
Missing docstring and return type annotation.

2022-06-02 15:51 UTC, adamegyed commented on src/util/Colors.ts
> +  if (cmax == 0) s = 0;
Replace `==` with `===`

2022-06-05 17:31 UTC, IanWoodard commented on src/components/browse/BrowseCard.tsx
> +    });
Should be fixed now, let me know!

2022-06-05 17:35 UTC, IanWoodard commented on src/pages/BlendPoolSelectPage.tsx
> +          {pools.map((pool, index, array) => {
good catch!

2022-06-05 18:04 UTC, IanWoodard commented on src/util/Colors.ts
> +function rgb_to_hsv(rgb: number[]) {
Added

2022-06-05 18:04 UTC, IanWoodard commented on src/util/Colors.ts
>  export async function getProminentColor(path: string) {
Added

2022-06-05 18:05 UTC, IanWoodard commented on src/util/Colors.ts
> +  if (cmax == 0) s = 0;
Done

2022-06-06 00:24 UTC, IanWoodard commented on src/pages/BlendPoolSelectPage.tsx
> +  }
I am still somewhat new to tailwind, but I can look into some more and find ways to clean things up

2022-06-06 00:29 UTC, IanWoodard commented
@adamegyed Addressed comments, take a look when you get the chance

2022-06-07 02:08 UTC, adamegyed approved these changes
LGTM

2022-06-07 02:08 UTC, adamegyed commented on src/components/browse/BrowseCard.tsx
> +  }, [token0, token1]);
Nicely handled!

2022-06-07 02:41 UTC, merged