Add Uniswap Widget, bumping wagmi to make provider compatible
aloelabs/aloe-web-interface pull request #89
Opened 2022-09-04 02:09 UTC by haydenshively

This was a pain but I think it's working. Can't use the newest version of the Uniswap Widget because it has some weird redux bug. And even the old version that I pinned is too new to work with our wagmi providers. So I had to go through and migrate wagmi stuff to the latest version.

2022-09-06 16:58 UTC, adamegyed requested changes
LGTM on functionality and styling. There are a few unused imports that were auto-detected, and I noticed the prop requirements of `SwapTab` needlessly included offchain pool stats. Please fix and this should be good to merge.

2022-09-06 16:58 UTC, adamegyed commented on src/components/pool/SwapTab.tsx
> +import { BlendPoolDrawData } from '../../data/BlendPoolDataResolver';
Unused import

2022-09-06 16:58 UTC, adamegyed commented on src/components/pool/SwapTab.tsx
> +  offChainPoolStats: OffChainPoolStats | undefined;
Unused prop field, remove it here and from the imports

2022-09-06 16:58 UTC, adamegyed commented on src/components/header/ConnectWalletButton.tsx
> +  const { data: connectData, error: connectError, connect, connectors, error, isLoading, pendingConnector } = useConnect({
can remove `connectData`, `error`, `isLoading`, and `pendingConnector`

2022-09-06 16:58 UTC, adamegyed commented on src/components/header/Header.tsx
> +  const { address, isConnecting, isDisconnected, connector: activeConnector } = useAccount();
Can remove `isConnecting`, `isDisconnected`

2022-09-06 16:58 UTC, adamegyed commented on src/pages/BlendPoolPage.tsx
> -  connector: Connector<any, any> | undefined;
Since type `Connector` is no longer used, can remove import.

2022-09-06 18:06 UTC, adamegyed reviewed
Thanks for fixing the linting notices and the prop dependency issue. I noticed something new when re-testing: the styling adjustments for the tab switcher seem to have some odd interaction with the swap modal's tooltip in what looks like mismatched z-indices and possibly some width constraints changing the aspect ratio for token logos.
<img width="476" alt="Screen Shot 2022-09-06 at 2 00 02 PM" src="https://user-images.githubusercontent.com/5456061/188707255-f3468576-d22b-41e6-90c7-cd0db46f036e.png">

Please fix, or add it as a GH issue and move to out-of-scope for this ticket.

2022-09-06 19:20 UTC, IanWoodard commented
@haydenshively I can go through and try to fix the styling for you if you would like

2022-09-07 20:20 UTC, haydenshively commented
Thanks Ian!

2022-09-07 20:20 UTC, merged